### ISSUE TITLE
AdminX 预览多出 / 

### ISSUE THREAD

**Issue by ocoke** [1689295608/AdminX#1]
预览链接变成：`https://www.ku.yfun.top/browser//index.html`

奇怪的 Bug。

**Comment by ocoke** [comment]
另外建议打开文件不要用 `window.open()`，不一会我的浏览器标签就全是（）

**Comment by 1689295608** [comment]
> 预览链接变成：`https://www.ku.yfun.top/browser//index.html`
> 
> 奇怪的 Bug。

已修复

**Comment by NekoWs** [comment]
> 另外建议打开文件不要用 `window.open()`，不一会我的浏览器标签就全是（）

已修复，新增 Shift + 点击文件在新窗口打开，否者在本窗口打开

**Comment by NekoWs** [comment]
> 预览链接变成：`https://www.ku.yfun.top/browser//index.html`
> 
> 奇怪的 Bug。

已修复，感谢反馈
